\n\n-- Drop all existing policies on users table to prevent conflicts\nDROP POLICY IF EXISTS "Users can read own data" ON users;
\nDROP POLICY IF EXISTS "Users can view their own profile" ON users;
\nDROP POLICY IF EXISTS "Admins can read all users" ON users;
\nDROP POLICY IF EXISTS "Admins can view all users" ON users;
\nDROP POLICY IF EXISTS "Allow user creation" ON users;
\n\n-- Create simple, non-recursive policies\nCREATE POLICY "Users can read own data"\n  ON users\n  FOR SELECT\n  TO authenticated\n  USING (auth.uid() = id);
\n\nCREATE POLICY "Allow user creation during signup"\n  ON users\n  FOR INSERT\n  TO authenticated\n  WITH CHECK (auth.uid() = id);
\n\nCREATE POLICY "Users can update own data"\n  ON users\n  FOR UPDATE\n  TO authenticated\n  USING (auth.uid() = id)\n  WITH CHECK (auth.uid() = id);
\n\n-- Simple admin policy without recursion\nCREATE POLICY "Service role can manage all users"\n  ON users\n  FOR ALL\n  TO service_role\n  USING (true)\n  WITH CHECK (true);
;
