name: Branch protection

on:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  administration: write

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: ['CI']
              },
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              enforce_admins: true,
              restrictions: null
            })
