name: DB Migrations

on:
  push:
    branches: [ main ]
    paths: [ "supabase/migrations/**" ]
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Vérifier que le secret n'est pas vide
      - name: Ensure SUPABASE_DB_URL is present
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "${SUPABASE_DB_URL}" ]; then
            echo "❌ SUPABASE_DB_URL is empty. Add it in GitHub → Settings → Secrets → Actions."
            exit 1
          fi
          echo "✅ SUPABASE_DB_URL provided (length: ${#SUPABASE_DB_URL})"

      # Résoudre l'IPv4 du host Supabase et construire une URL forçant l'IPv4
      - name: Build IPv4 connection URL
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          # Extraire le host de l'URL (entre '@' et ':5432')
          HOST=$(printf "%s" "$SUPABASE_DB_URL" | sed -E 's/^.*@([^:/?]+):5432.*$/\1/')
          if [ -z "$HOST" ]; then
            echo "❌ Unable to extract host from SUPABASE_DB_URL"
            exit 1
          fi

          # Récupérer la première IPv4 via getent (présent sur ubuntu-latest)
          IPV4=$(getent ahostsv4 "$HOST" | awk '{print $1; exit}')
          if [ -z "$IPV4" ]; then
            echo "❌ No IPv4 found for $HOST"
            exit 1
          fi
          echo "🔎 $HOST → IPv4 = $IPV4"

          # Ajouter hostaddr=<IPv4> (et sslmode=require s'il manque)
          URL="$SUPABASE_DB_URL"
          case "$URL" in
            *\?*) SEP="&" ;;
            *)    SEP="?" ;;
          esac

          case "$URL" in
            *sslmode=*) URL_SSL="$URL" ;;
            *)          URL_SSL="${URL}${SEP}sslmode=require"; SEP="&" ;;
          esac

          DB_URL_V4="${URL_SSL}${SEP}hostaddr=${IPV4}"
          echo "DB_URL_V4=$DB_URL_V4" >> $GITHUB_ENV
          echo "✅ Will use IPv4-forced URL."

      - name: Show pending migrations
        run: supabase migration status --db-url "${DB_URL_V4}" || true

      - name: Apply migrations
        run: supabase migration up --db-url "${DB_URL_V4}" --include-all --yes
