name: DB Migrations (Supabase)

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: supabase-db-migrations
  cancel-in-progress: false

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Check SUPABASE_DB_URL secret
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -z "$SUPABASE_DB_URL" ]; then
            echo "❌ Missing SUPABASE_DB_URL secret"; exit 1
          fi
          echo "✅ Secret present"

      # Applique les migrations locales côté base (idempotent)
      - name: Apply migrations
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          supabase db push --db-url "$SUPABASE_DB_URL" --include-all --yes
