name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]
    paths:
      - "supabase/functions/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Lie le projet Supabase avec ton repo via le token
      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          supabase link --project-ref "$SUPABASE_PROJECT_REF" --access-token "$SUPABASE_ACCESS_TOKEN"

      # (OPTIONNEL) Synchroniser des secrets runtime pour tes fonctions
      # Renseigne ces secrets dans GitHub si tu veux piloter depuis CI:
      # SB_URL, SB_SERVICE_ROLE_KEY, STRIPE_SECRET, WEBHOOK_SECRET, RESEND_API_KEY, FROM_EMAIL
      - name: Sync Edge Function secrets (optional)
        env:
          SB_URL:              ${{ secrets.SB_URL }}
          SB_SERVICE_ROLE_KEY: ${{ secrets.SB_SERVICE_ROLE_KEY }}
          STRIPE_SECRET:       ${{ secrets.STRIPE_SECRET }}
          WEBHOOK_SECRET:      ${{ secrets.WEBHOOK_SECRET }}
          RESEND_API_KEY:      ${{ secrets.RESEND_API_KEY }}
          FROM_EMAIL:          ${{ secrets.FROM_EMAIL }}
        run: |
          set -e
          tmp="$(mktemp)"
          [ -n "$SB_URL" ] && echo "SB_URL=$SB_URL" >> "$tmp"
          [ -n "$SB_SERVICE_ROLE_KEY" ] && echo "SB_SERVICE_ROLE_KEY=$SB_SERVICE_ROLE_KEY" >> "$tmp"
          [ -n "$STRIPE_SECRET" ] && echo "STRIPE_SECRET=$STRIPE_SECRET" >> "$tmp"
          [ -n "$WEBHOOK_SECRET" ] && echo "WEBHOOK_SECRET=$WEBHOOK_SECRET" >> "$tmp"
          [ -n "$RESEND_API_KEY" ] && echo "RESEND_API_KEY=$RESEND_API_KEY" >> "$tmp"
          [ -n "$FROM_EMAIL" ] && echo "FROM_EMAIL=$FROM_EMAIL" >> "$tmp"
          if [ -s "$tmp" ]; then
            cat "$tmp" | supabase secrets set --env-file -
            echo "✅ Function secrets updated in Supabase."
          else
            echo "ℹ️ No secrets provided from GitHub; skipping."
          fi
          rm -f "$tmp"

      # Déploie TOUTES les fonctions présentes sous supabase/functions/*
      - name: Deploy all functions
        run: |
          set -e
          shopt -s nullglob
          for d in supabase/functions/*/ ; do
            fn="$(basename "$d")"
            echo "🚀 Deploying: $fn"
            supabase functions deploy "$fn"
          done
          echo "✅ All functions deployed."
